rx-training/Training-Jan-2021

Modules/Redmine-Git/README.md

REFS: #5 and fixes #5 (New Repository - 1)

REFS: #5 and fixes #5 (New Repository)

---

Modules/Redmine-Git/Day1/Disha-Shah/index.html

Created index.html file

---

Modules/Redmine-Git/Day1/Index.html

REFS: #5 and fixes #5 (Create index.html file)

REFS: #5 and fixes #5 (Create index.html file)

---

Modules/Redmine-Git/Day1/Namra/index.html

REFS: #5 and fixes #5

---

Modules/Redmine-Git/Day1/Ankur-Chovatiya/Demo.html
Modules/Redmine-Git/Day1/Ankur-Chovatiya/Practical/demo.html
README.md

ankur Chovatiya Folder is crated.

day work final Pull

---

Modules/Redmine-Git/Day1/unnati-shah/index-pull.html
index1.html

Day1_unnatishah

---

Modules/Redmine-Git/Day1/Vatsal-Patel/Profile.html
Modules/Redmine-Git/Day1/Vatsal-Patel/index.css

Mam , I make a simple page related to the git/github

REFS #5 and fixes #5 ( Create a simple page.)

---

Modules/Redmine-Git/Day1/Shekhar Chawla/index.html

REFS #5 and fixes #5

---

Modules/Redmine-Git/Day1/Tirth-patel/exercise.html

REFS: #4 and fixes #4
done cloning and pushing

final commit

---

Modules/Redmine-Git/Day1/Index.html
Modules/Redmine-Git/Day1/Mitul-Soni/index.html
Modules/Redmine-Git/Day1/index.html

REFS: #5 and fixes #5(Day1)

---

Modules/Redmine-Git/Day1/Karan-Chauhan/index.html

REFS: #5 and fixes #5(day-1 task complete)

REFS: #5 and fixes #5(day-1 task completed)

---

Modules/Redmine-Git/Day1/Milit-Panchasara/index.html

REFS: #5 and fixes #5 (index.html added)

REFS: #5 and fixes #5 (index.html added)

---

Modules/Redmine-Git/Day1/Harsh_Bhavsar/index.html
Modules/Redmine-Git/Day2/Harsh-bhavsar/demo.html

REFS : #5 and fixes #5

---

Modules/Redmine-Git/Day1/Index.html
Modules/Redmine-Git/Day1/sachin_sharma/index.html

(cmd line task yesterday and today task create branch and merge to main branch with commit and push using cmd and vs code)

REFS #5 and FIxes #5 (cmd line task yesterday and today task branch)

---

Modules/Html/Day3/Assignment/Nav.html
Modules/Html/Day3/Assignment/login.html
Modules/Html/Day3/Assignment/news.html
Modules/Html/Day3/Practical/ReportCard.html
Modules/Html/Day3/Practical/department.html
Modules/Html/Day3/layout.html

Final pull Request Day 3 Work Done

REFS: #20 and fixes #20 ( day 3 work done )

---

Modules/JavaScript/Day16/Milit-Panchasara/assignment/assignment.html
Modules/JavaScript/Day16/Milit-Panchasara/practice/practice1.html
Modules/JavaScript/Day16/Milit-Panchasara/practice/practice2.html
Modules/JavaScript/Day17/Milit-Panchasara/assignment/assignment.html
Modules/JavaScript/Day17/Milit-Panchasara/practice/event-listeners-practice.html
Modules/JavaScript/Day17/Milit-Panchasara/practice/practice1.html
Modules/JavaScript/Day17/Milit-Panchasara/practice/practice2.html

completed day16 assignment, practices, and extra work

REFS: #45 and fixes #45

---

Modules/SQL/Day2/Smit vadhiya/SQL-Day2-Assignments.sql

refs :#121 and fixes #121 SQL Day2 Task done

---

Modules/SQL/Day2/Namra/Assignment.sql
Modules/SQL/Day2/Namra/Practice.sql
Modules/SQL/Day3/Namra/Assignment.sql
Modules/SQL/Day3/Namra/Practical.sql

REFS : #121 and fixes #121 (Day2 Work)

---

Modules/Bootstrap/day12/Smit vadhiya/Assignment/looplab/src/.vscode/settings.json
Modules/Project/Smit vadhiya/project 2(Detroit Bank)/src/.vscode/settings.json
Modules/SQL/Day2/Smit vadhiya/SQL-Day2-Assignments.sql
Modules/SQL/Day3/Smit vadhiya/SQLDay3Assignment.sql

Day-3 ka work friday ko hi commit ho gaya tha to wo bhi sath hi aa gaya he isme

Day 2 comments resolved

---

Modules/SQL/Day1/jevik-raiyani/Practical-Assignment/SQLQuery1.sql
Modules/SQL/Day2/jevik-raiyani/Assignment/AssignmentD2.sql
Modules/SQL/Day2/jevik-raiyani/Practice/practiceD2.sql

REFS: #121 and fixes #121

---

Modules/SQL/Day4/jevik-raiyani/Assignment/AssignmentD4.sql
Modules/SQL/Day4/jevik-raiyani/Practice/practiceD4.sql
Modules/SQL/Day5/jevik-raiyani/Assignment/AssignmentD5.sql
Modules/SQL/Day5/jevik-raiyani/Practice/practiceD5.sql
Modules/SQL/Day6/jevik-raiyani/Assignment/AssignmentD6.sql
Modules/SQL/Day6/jevik-raiyani/Practice/practiceD6.sql
Modules/SQL/Day7/jevik-raiyani/Assignment/AssignmentD7.sql
Modules/SQL/Day7/jevik-raiyani/Practice/practiceD7.sql
Modules/SQL/Day8/jevik-raiyani/Assignment/AssignmentD8.sql
Modules/SQL/Day8/jevik-raiyani/Practice/practiceD8.sql

REFS: #126 and fixes #126

---

Modules/Bootstrap/Day9/Smit vadhiya/Assignment/alert_progress.html
Modules/SQL/Day4/Smit vadhiya/SQLAssignmentDay4.sql
Modules/SQL/Day4/Smit vadhiya/SQLPracticeHandsOn.sql
Modules/SQL/Day5/Smit vadhiya/SQLPracticeDay5.sql
Modules/SQL/Day5/Smit vadhiya/SQLQueryNotepad.sql
Modules/SQL/Day5/Smit vadhiya/SQLTrainingSiteAssignmentDay5.sql
Modules/SQL/Day6/Smit vadhiya/SQLAssignment.sql
Modules/SQL/Day6/Smit vadhiya/SQLSubQueriesDay6.sql
Modules/SQL/Day6/Smit vadhiya/SQLViewTableDay6.sql
Modules/SQL/Day7/Smit vadhiya/SQLAssignmentDay7.sql
Modules/SQL/Day7/Smit vadhiya/SQLDay7Practice.sql
Modules/SQL/Day7/Smit vadhiya/SQLTrainingSiteAssignmentDay7.sql
Modules/SQL/Day8/Smit vadhiya/SQLAssignmentDay8.sql
Modules/SQL/Day8/Smit vadhiya/SQLPracticeDay8.sql
Modules/SQL/Day8/Smit vadhiya/mcqtask.txt

REFS: #126 AND FIXES #126 day-4 task done

---

Modules/SQL/Day4/Namra/Assignment.sql
Modules/SQL/Day4/Namra/Practice.sql
Modules/SQL/Day5/Namra/Assignment.sql
Modules/SQL/Day5/Namra/Practice.sql
Modules/SQL/Day6/Namra/Assignment.sql
Modules/SQL/Day6/Namra/Practice.sql
Modules/SQL/Day7/Namra/Assignment.sql
Modules/SQL/Day7/Namra/Practical.sql
Modules/SQL/Day8/Namra/Assignment.sql
Modules/SQL/Day8/Namra/Practice.sql

Learned Ranking function, Aggegreate function, and Group By, ROLLUP, and Having. Learned usage of it. Implemented practice exercise work by referring videos and ppt posted on site. Then, I completed an assignment based on these all topics.

REFS : #126 andd fixes #126 (Day 4 SQL)
